# da-content-ams — wrangler.toml.tpl
#
# Deploy flow (mirrors the helix-cloudflare-*-ams workers):
#   wrangler.toml.tpl (this file, committed — NO customer/env values)
#     → scripts/render-wrangler.js: substitutes $VAR placeholders from env
#   wrangler.toml (generated, gitignored)
#     → wrangler deploy -c wrangler.toml
#
# Required env vars — sourced from ams-eds-terraform's environments/<env>.env
# (generated by scripts/generate-env-file.sh for content_source=da):
#   NODE_ENV                     short env name (worker name suffix + service binding)
#   CLOUDFLARE_ACCOUNT_ID        Cloudflare account ID
#   DA_DOMAIN                    DA domain (route host, ADMIN_URL, zone)
#   AEM_BUCKET_NAME              DA content R2 bucket name
#   HELIX_ADMIN_IPS              NAT egress IPs of helix3--admin (from the DA VPC)
#   (ADMIN_EXCEPTED_ORGS is a fixed default below — not env-driven)
#
# Secrets (S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY) are pushed via `wrangler secret
# put` by ams-eds-terraform's populate-secrets.sh — not templated here.

name = "da-content-ams-${NODE_ENV}"
main = "src/index.js"
compatibility_date = "2026-03-04"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
keep_vars = true
workers_dev = false
preview_urls = false

routes = [
  { pattern = "content.${DA_DOMAIN}/*", zone_name = "${DA_DOMAIN}" }
]

services = [
  { binding = "daadmin", service = "da-admin-ams-${NODE_ENV}" }
]

[dev]
port = 8788

[vars]
ENVIRONMENT = "${NODE_ENV}"
AEM_BUCKET_NAME = "${AEM_BUCKET_NAME}"
ADMIN_URL = "admin.${DA_DOMAIN}"
ADMIN_EXCEPTED_ORGS = "adobe,ams-eds,ssa-eds"
CF_ACCOUNT_ID = "${CLOUDFLARE_ACCOUNT_ID}"

# Helix Admin IP allowlist (comma-separated NAT egress IPs of helix3--admin).
# https://www.aem.live/docs/security#backends-with-ip-filtering
HELIX_ADMIN_IPS = "${HELIX_ADMIN_IPS}"
